from dataclasses import dataclass

from astra.cpu.alu_control import ALUControl, ALUOperation
from astra.isa.instructions import Instruction, Opcode


@dataclass(frozen=True)
class ControlSignals:
    """
    Control signals generated by the CPU Control Unit.

    These signals tell the datapath and other CPU components
    what operation should be performed for an instruction.
    """

    alu_operation: ALUOperation | None

    register_write: int

    memory_read: int

    memory_write: int

    pc_load: int

    pc_increment: int

    halt: int


class ControlUnit:
    """
    Converts an instruction into CPU control signals.

    The Control Unit is the main translation layer between
    the decoded ISA instruction and the hardware datapath.

    ALU instructions:
        ADD
        SUB
        AND
        OR
        XOR
        NOT

    Memory instructions:
        LOAD
        STORE

    Control-flow instruction:
        JUMP

    Processor-control instruction:
        HALT
    """

    def __init__(self) -> None:
        """
        Initialize the Control Unit.

        ALU operations are obtained from ALUControl so that
        the mapping between ISA operations and ALU operations
        remains centralized.
        """

        self.alu_control = ALUControl()

        self.controls = {
            Opcode.ADD: ControlSignals(
                alu_operation=self.alu_control.operation(Opcode.ADD),
                register_write=1,
                memory_read=0,
                memory_write=0,
                pc_load=0,
                pc_increment=1,
                halt=0,
            ),

            Opcode.SUB: ControlSignals(
                alu_operation=self.alu_control.operation(Opcode.SUB),
                register_write=1,
                memory_read=0,
                memory_write=0,
                pc_load=0,
                pc_increment=1,
                halt=0,
            ),

            Opcode.AND: ControlSignals(
                alu_operation=self.alu_control.operation(Opcode.AND),
                register_write=1,
                memory_read=0,
                memory_write=0,
                pc_load=0,
                pc_increment=1,
                halt=0,
            ),

            Opcode.OR: ControlSignals(
                alu_operation=self.alu_control.operation(Opcode.OR),
                register_write=1,
                memory_read=0,
                memory_write=0,
                pc_load=0,
                pc_increment=1,
                halt=0,
            ),

            Opcode.XOR: ControlSignals(
                alu_operation=self.alu_control.operation(Opcode.XOR),
                register_write=1,
                memory_read=0,
                memory_write=0,
                pc_load=0,
                pc_increment=1,
                halt=0,
            ),

            Opcode.NOT: ControlSignals(
                alu_operation=self.alu_control.operation(Opcode.NOT),
                register_write=1,
                memory_read=0,
                memory_write=0,
                pc_load=0,
                pc_increment=1,
                halt=0,
            ),

            Opcode.LOAD: ControlSignals(
                alu_operation=None,
                register_write=1,
                memory_read=1,
                memory_write=0,
                pc_load=0,
                pc_increment=1,
                halt=0,
            ),

            Opcode.STORE: ControlSignals(
                alu_operation=None,
                register_write=0,
                memory_read=0,
                memory_write=1,
                pc_load=0,
                pc_increment=1,
                halt=0,
            ),

            Opcode.JUMP: ControlSignals(
                alu_operation=None,
                register_write=0,
                memory_read=0,
                memory_write=0,
                pc_load=1,
                pc_increment=0,
                halt=0,
            ),

            Opcode.HALT: ControlSignals(
                alu_operation=None,
                register_write=0,
                memory_read=0,
                memory_write=0,
                pc_load=0,
                pc_increment=0,
                halt=1,
            ),
        }

    def decode(self, instruction: Instruction) -> ControlSignals:
        """
        Generate control signals for an instruction.

        Args:
            instruction:
                A valid Astra Instruction.

        Returns:
            ControlSignals corresponding to the instruction.

        Raises:
            TypeError:
                If instruction is not an Instruction.
        """

        if not isinstance(instruction, Instruction):
            raise TypeError("instruction must be an Instruction")

        return self.controls[instruction.opcode]